# Generated by Django 5.0.2 on 2024-03-05 13:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluraflix', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
